# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lap4TkAwQ77uIZY4hdxasA5ADUHGDcDv
"""

a,b,c=map(int,input().split())
print((a+b+c)/3)



"""vowels"""

s="butterfly"
v="aeiou"
count=0
for i in s:
  if i in v:
    count+=1
    print(i)
print(count)

"""swap"""

a,b=map(int,input().split())
print(a,b)
a,b=b,a
print(a)
print(b)

"""temp convertion"""

c = float(input())
f = (9/5 * c) + 32
print(f)

"""prime num"""

for n in if n > 1:
        prime = True
        for i in range(2, n):
            if n % i == 0:
                prime = False
                break
        if prime:
            print(n)range(1, 51):

"""amstrong"""

n = int(input())
temp = n
sum = 0
while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10
if sum == n:
    print("Armstrong")
else:
    print("Not Armstrong")

"""largest of two"""

a=int(input())
b=int(input())
if a>b:
  print(" a is the largest")
else:
  print("b is the largest")

"""factorial"""

n=int(input())
fact=1
for i in range(1,n + 1):
  fact=fact*i
print(fact)

"""palindrome"""

n=input()
if n==n[::-1]:
  print("palindrome")
else:
  print("no")

"""temp converstion"""

f=float(input())
c=(f-32)*(5/9)
print(c)

"""sum of digit"""

t=int(input())
for i in range(t):
  n=input()
  sum=0
  for d in n:
    sum= sum + int(d)
  print(sum)

"""print first and last digit"""

n=input()
first=n[0]
last=n[-1]
print(first,last)

n=int(input())
words=["one","two","three","four","five","six","seven","eight","nine"]
print(words[n-1])

"""gcd"""

a,b=map(int,input().split())
while b!=0:
  a,b=a,a%b
print(a)

"""lcm"""

a,b=map(int,input().split())
x=a
y=b
while y!=0:
  x,y=y,x%y
gcd=x
lcm=(a*b)//x
print(lcm)

"""calculator"""

a,b=map(int,input().split())
c=input("enter choice a.add b.sub c.mul d.div")
if c=="a":
  print(a+b)
if c=="b":
  print(a-b)
if c=="c":
  print(a*b)
if c=="d":
  print(a/b)

"""largest and smallest"""

n=[3,17,29,7,65,92]
print("largest:",max(n))
print("smallest:",min(n))

"""positive negative"""

n=int(input())
if n<0:
  print("negative")
elif n>0:
  print("positive")
else:
  print("zero")

"""leap year"""

n=int(input())
if n%4==0 and n%100!=0 or n%400==0:
  print("leap year")
else:
  print("not a leap year")

"""num to words"""

num = int(input())

ones = ["Zero", "One", "Two", "Three", "Four",
        "Five", "Six", "Seven", "Eight", "Nine"]

teens = ["Ten", "Eleven", "Twelve", "Thirteen", "Fourteen",
         "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"]

tens = ["", "", "Twenty", "Thirty", "Forty",
        "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]

if num < 10:
    print(ones[num])

elif num < 20:
    print(teens[num - 10])

elif num < 100:
    t = num // 10
    o = num % 10

    if o == 0:
        print(tens[t])
    else:
        print(tens[t], ones[o])

elif num < 1000:
    h = num // 100
    rem = num % 100

    print(ones[h], "Hundred", end=" ")

    if rem < 10:
        print(ones[rem])

    elif rem < 20:
        print(teens[rem - 10])

    else:
        t = rem // 10
        o = rem % 10

        if o == 0:
            print(tens[t])
        else:
            print(tens[t], ones[o])

"""odd or even"""

n=int(input())
if n==0:
  print("neither odd nor even")
elif n%2==0:
  print("even")
else:
  print("odd")

"""anagram"""

s=input()
t=input()
if len(s)!=len(t):
  print("not anagram")
elif sorted(s) == sorted(t):
  print("anagram")
else:
  print("not anagram")

"""pattern 1"""

for  i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

"""pattern 2"""

for i in range(5,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

"""pattern 3"""

for i in range(1,6):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

"""pattern 4"""

n=3
for i in range(n):
  for j in range(n-i-1):
    print(" ",end=" ")
  for j in range(2*i+1):
    print("#",end=" ")
  print()
for i in range(n-1):
  for j in range(i+1):
    print(" ",end=" ")
  for j in range(2*(n-i-1)-1):
    print("#",end=" ")
  print()

n=3
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "*(n-i)+"* "*i)

n=6
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)

n=6
for i in range(1,n+1):
  print(" "*(n-1)+"* "*i)

n=6
for i in range(n,0,-1):
  print(" "*(n-1)+"* "*i)

n=list(map(int,input().split()))
m=sorted(n,reverse=True)
print(m[:3])

s1 = input()
s2 = input()
if len(s1) != len(s2):
    print("Not Anagram")
else:
    c1 = {}
    c2 = {}
    for i in s1:
        c1[i] = c1.get(i, 0) + 1
    for i in s2:
        c2[i] = c2.get(i, 0) + 1
    if c1 == c2:
        print("Anagram")
    else:
        print("Not Anagram")

n = int(input())

if n > 0 and (n & (n - 1)) == 0:
    print("Power of 2")
else:
    print("Not Power of 2")

t=int(input())
for i in range(t):
    n=input()
    print(n.count('4'))

"""num and rev are prime"""

n = int(input())
rev = int(str(n)[::-1])

prime1 = True
for i in range(2, n):
    if n % i == 0:
        prime1 = False
        break

prime2 = True
for i in range(2, rev):
    if rev % i == 0:
        prime2 = False
        break

if prime1 and prime2:
    print("yes")
else:
    print("no")

"""adam num"""

n = int(input())

sq1 = n * n

rev_n = int(str(n)[::-1])
sq2 = rev_n * rev_n

rev_sq1 = int(str(sq1)[::-1])

if rev_sq1 == sq2:
    print("Adam Number")
else:
    print("Not Adam Number")

"""duck num(contains 0)"""

n=input()
for i in range(int(n)):
  if i == 0:
    print("duck num")
    break
  else:
    print("not duck num")

"""circular prime:All rotations of number should be prime"""

n = input()
flag = True

for i in range(len(n)):
    r = n[i:] + n[:i]
    num = int(r)

    c = 0
    for j in range(1, num + 1):
        if num % j == 0:
            c += 1

    if c != 2:
        flag = False
        break

if flag:
    print("Circular Prime")
else:
    print("Not Circular Prime")

"""peterson num:Sum of factorial of digits equals original number."""

n = int(input())
temp = n
s = 0
def fact(n):
    f = 1
    for i in range(1, n + 1):
        f = f * i
    return f
while temp > 0:
    d = temp % 10
    s = s + fact(d)
    temp = temp // 10
if s == n:
    print("Peterson Number")
else:
    print("Not Peterson Number")

"""automorphic num(Square of number ends with same number)"""

n = int(input())
m = n * n
if str(m).endswith(str(n)):
    print("Automorphic Number")
else:
    print("Not Automorphic Number")

"""spiral matrix"""



s = input()

for i in range(len(s)):
    t = s[:i] + s[i+1:]
    if t == t[::-1]:
        print("YES")
        break
else:
    print("NO")

n = int(input())
a = list(map(int, input().split()))

total = n * (n + 1) // 2
print(total - sum(a))

a = list(map(int, input().split()))

flag = False

for i in range(len(a)):
    for j in range(i + 1, len(a)):
        if a[i] == a[j]:
            flag = True
            break
    if flag:
        break

if flag:
    print("Duplicate Found")
else:
    print("No Duplicate")

tags = input().split()
freq = {}
for tag in tags:
    if tag in freq:
        freq[tag] += 1
    else:
        freq[tag] = 1
high = max(freq.values())
result = []
for tag in freq:
    if freq[tag] == high:
        result.append(tag)

print(min(result))

n=int(input())
print(n)

t = int(input())
for i in range(t):
    a, b = map(int, input().split())
    print(a + b)

x, y = input().split()
x = int(x)
y = float(y)
if x % 5 == 0 and y >= x + 0.50:
    y = y - x - 0.50
print("{:.2f}".format(y))

t = int(input())
for i in range(t):
    a, b = map(int, input().split())
    print(a % b)

t=int(input())
for i in range(t):
    n = input()

    first = int(n[0])
    last = int(n[-1])

    print(first + last)

n, k) = map(int, input().split())

ans = 0

for i in range(n):
	x = int(input())
	if x % k == 0:
		ans += 1

print(ans)

n = int(input())

a = list(map(int, input().split()))

even = 0
odd = 0

for i in a:
    if i % 2 == 0:
        even += 1
    else:
        odd += 1

if even > odd:
    print("READY FOR BATTLE")
else:
    print("NOT READY")

t=int(input())
for i in range(t):
    n=input()
    print(int(n[::-1]))

t=int(input())
for i in range(t):
    n=input()
    print(int(n[::-1]))

t=int(input())
for i in range(t):
    n=int(input())
    fact=1
    for v in range(1,n+1):
        fact=fact*v
    print(fact)

import math

t = int(input())

for i in range(t):
    n = int(input())

    print(math.isqrt(n))

t=int(input())
for i in range(t):
   a = list(map(int, input().split()))
   largest = max(a)
   a.remove(largest)
   second_largest = max(a)
   print(second_largest)

t=int(input())
for i in range(t):
    a,b,c=map(int,input().split())
    if a+b+c==180:
        print("YES")
    else:
        print("NO")

t = int(input())

for i in range(t):
    n = int(input())
    f = 1

    for j in range(1, n + 1):
        f = f * j

    print(f)

t=int(input())
for i in range(t):
    n=int(input())
    if n<10:
        print("Thanks for helping Chef!")
    else:
        print("-1")

t = int(input())

for _ in range(t):
    n, k = map(int, input().split())
    arr = list(map(int, input().split()))

    count = 0
    for x in arr:
        if (x + k) % 7 == 0:
            count += 1

    print(count)

# cook your dish here
n = int(input())

sum1 = 0
sum2 = 0
max_lead = 0
winner = 0

for _ in range(n):
    s, t = map(int, input().split())

    sum1 += s
    sum2 += t

    if sum1 > sum2:
        lead = sum1 - sum2
        if lead > max_lead:
            max_lead = lead
            winner = 1
    else:
        lead = sum2 - sum1
        if lead > max_lead:
            max_lead = lead
            winner = 2

print(winner, max_lead)

# cook your dish here
t= int(input())
for i in range(t):
    n=int(input())
    if n<1500:
        hra=(n*10)/100
        da=(n*90)/100
    elif n>=1500:
        hra=500
        da=n*98/100
    salary=n+hra+da
    print(salary)

# cook your dish here
t=int(input())
for i in range(t):
    n=input()
    m=n[::-1]
    if m==n:
        print("wins")
    else:
        print("loses")

# cook your dish here
t=int(input())
for i in range(t):
    a,b,c=input().split()
    a=int(a)
    b=float(b)
    c=int(c)
    if a>50 and b<0.7 and c>5600:
        print("10")
    elif a>50 and b<0.7:
        print("9")
    elif b<0.7 and c>5600:
        print("8")
    elif a>50 and c>5600:
        print("7")
    elif a>50 or b<0.7 or c>5600:
        print("6")
    else:
        print("5")

# cook your dish here
c=input()
v="aeioAEIOU"
if c in v:
    print("vowel")
else:
    print("consonant")

# cook your dish here
t=int(input())
for i in range(t):
    id=input()
    if id=="B" or id=="b":
        print("BattleShip")
    if id=="C" or id=="c":
        print("Cruiser")
    elif id=="D" or id=="d":
        print("Destroyer")
    elif id=="F" or id=="f":
        print("Frigate")

# cook your dish here
t = int(input())
for _ in range(t):
    p = int(input())
    count = 0
    count += p // 2048
    p %= 2048
    while p > 0:
        if p % 2 == 1:
            count += 1
        p //= 2

    print(count)

# cook your dish here
t = int(input())
for _ in range(t):
    p = int(input())
    count = 0
    count += p // 2048
    p %= 2048
    while p > 0:
        if p % 2 == 1:
            count += 1
        p //= 2

    print(count)

# cook your dish here
t=int(input())
for i in range(t):
    n=input()
    print(n.count('4'))