# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX-6xDvdz9j3HfTi47Nng1zbFgm_C9gA
"""

import os
os.environ['KAGGLE_USERNAME'] ='hams'
os.environ['KAGGLE_KEY'] = 'KGAT_445f66f5ad730e867873287ea42987b7'

!pip install kaggle

!kaggle datasets download -d 'sathishdhuda/student-dataset'

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

!pip install openpyxl
!unzip -o /content/student-dataset.zip
df = pd.read_excel('/content/Student.xlsx')

print(df.head())
print(df.columns)

df = df.dropna()

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

svm_model = SVC(kernel='rbf')

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

new_student = [[1, 15, 75, 80, 85, 90]] # Assuming 1 is encoded Name, 15 is a dummy RollNo, and others are scores for AI, DBMS, PP, WP

new_student = scaler.transform(new_student)

prediction = svm_model.predict(new_student)

print("Prediction:", prediction)

print(df.shape)
print(df.columns)
print(y.unique())
print(y.value_counts())
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def grade(mark):
    if mark >= 50:
        return 'Pass'
    else:
        return 'Fail'

df['Grade'] = df['EMSML'].apply(grade)

X = df[['AI', 'DBMS', 'PP', 'WP']]
y = df['Grade']

le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

svm_model = SVC(kernel='rbf')

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

new_student = [[85, 78, 90, 88]]

new_student = scaler.transform(new_student)

prediction = svm_model.predict(new_student)

print("Predicted Result:", le.inverse_transform(prediction)[0])